build:
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
filter:
    paths: [src/*]
checks:
    php:
        code_rating: true
duplication: true
